/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.yaml  instead.
 *  Run   pnpm check-config  to validate before deploying.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from "@/lib/themes";
import rawConfigYaml from "../portfolio.config.yaml";

const rawConfig = rawConfigYaml as unknown as {
  name:           string;
  title:          string;
  tagline:        string;
  email:          string;
  phone?:         string;
  location:       string;
  avatarUrl:      string;
  resumeUrl:      string;
  resumeFileName: string;
  openToWork:     boolean;
  defaultTheme:   string;
  colorPreset:    string;
  resumeTheme?:   { twoColumn?: string; classic?: string };
  customColors?:  PresetPalette;
  social:         Record<string, string>;
  sections:       { id: string; show: boolean }[];
  about:          string;
  languages:      { name: string; level: string }[];
  skills:         { category: string; items: string[] }[];
  experience:     { company: string; role: string; period: string; description: string; highlights?: string[] }[];
  projects:       { name: string; description: string; tags: string[]; liveUrl: string; repoUrl: string; featured: boolean }[];
  education:      { institution: string; degree: string; period: string }[];
  certifications: { title: string; issuer: string; date: string; credentialUrl: string; badgeUrl: string; tags: string[] }[];
  testimonials:   { name: string; title: string; company: string; relationship: string; quote: string; photoUrl: string }[];
};

export type SectionId =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "education"
  | "certifications"
  | "testimonials"
  | "contact";

export interface SectionEntry {
  id:   SectionId;
  show: boolean;
}

export interface Language {
  name:  string;
  level: string;
}

export interface Certification {
  title:         string;
  issuer:        string;
  date:          string;
  credentialUrl: string;
  badgeUrl:      string;
  tags:          string[];
}

export interface Testimonial {
  name:         string;
  title:        string;
  company:      string;
  relationship: string;
  quote:        string;
  photoUrl:     string;
}

export interface ResumeTheme {
  twoColumn: ColorPreset;
  classic:   ColorPreset;
}

export const config = {
  ...rawConfig,
  colorPreset:    rawConfig.colorPreset  as ColorPreset,
  defaultTheme:   rawConfig.defaultTheme as "system" | "light" | "dark",
  sections:       rawConfig.sections     as SectionEntry[],
  languages:      (rawConfig.languages      ?? []) as Language[],
  certifications: (rawConfig.certifications ?? []) as Certification[],
  testimonials:   (rawConfig.testimonials   ?? []) as Testimonial[],
  customColors:   rawConfig.customColors,
  resumeTheme: {
    twoColumn: (rawConfig.resumeTheme?.twoColumn ?? rawConfig.colorPreset) as ColorPreset,
    classic:   (rawConfig.resumeTheme?.classic   ?? rawConfig.colorPreset) as ColorPreset,
  } as ResumeTheme,
};
