/**
 * ============================================================
 *  PORTFOLIO CONFIGURATION — DO NOT EDIT THIS FILE
 *
 *  Edit  portfolio.config.json  instead.
 *  That file has no code syntax — just fill in your details.
 * ============================================================
 */

import type { ColorPreset, PresetPalette } from "@/lib/themes";
import rawConfig from "../portfolio.config.json";

export type SectionId =
  | "about"
  | "skills"
  | "experience"
  | "projects"
  | "education"
  | "certifications"
  | "testimonials"
  | "contact";

export interface SectionEntry {
  id:   SectionId;
  show: boolean;
}

export interface Certification {
  title:         string;
  issuer:        string;
  date:          string;
  credentialUrl: string;
  badgeUrl:      string;
  tags:          string[];
}

export interface Testimonial {
  name:         string;
  title:        string;
  company:      string;
  relationship: string;   // e.g. "Manager", "Colleague", "Client"
  quote:        string;
  photoUrl:     string;   // URL to headshot — leave empty for initials
}

export const config = {
  ...rawConfig,
  colorPreset:    rawConfig.colorPreset  as ColorPreset,
  defaultTheme:   rawConfig.defaultTheme as "system" | "light" | "dark",
  sections:       rawConfig.sections     as SectionEntry[],
  certifications: (rawConfig.certifications ?? []) as Certification[],
  testimonials:   (rawConfig.testimonials ?? [])   as Testimonial[],
  customColors:   (rawConfig as unknown as { customColors?: PresetPalette }).customColors,
};
